### ISSUE TITLE
Need to create /etc/paging/.config & /etc/paging.wav for script to work properly on OrangePI PC

### ISSUE THREAD

**Issue by danry25** [AccelerateNetworks/PagingServer#15]
To get pulse to run correctly on the OrangePI (without pulse complaining "E: [pulseaudio] core-util.c: Failed to create secure directory (/home/paging/.config/pulse): No such file or directory" when started by systemd) /etc/paging/.config needs to exist. Also, /etc/paging.wav needs to be put in place and enabled, otherwise the paging.service itself will hang & fail or hang for 10 seconds then connect the call.

**Comment by danry25** [comment]
To get pulse to run correctly on the OrangePI (without pulse complaining "E: [pulseaudio] core-util.c: Failed to create secure directory (/home/paging/.config/pulse): No such file or directory" when started by systemd) /etc/paging/.config needs to exist. Also, /etc/paging.wav needs to be put in place and enabled, otherwise the paging.service itself will hang & fail or hang for 10 seconds then connect the call.

**Comment by mk-fg** [comment]
> without pulse complaining "E: [pulseaudio] core-util.c: Failed to create secure directory (/home/paging/.config/pulse): No such file or directory"

Ah yeah, apparently [install scripts](https://github.com/AccelerateNetworks/PagingServer/blob/master/setup-scripts/install.debian_jessie.from_debs.sh#L35-L42) either create user or its home dir but not both on the first run, a mistake.

> Also, /etc/paging.wav needs to be put in place and enabled

Same issue was actually pointed-out in #14, I think, and should be fixed wrt operation without klaxon file, at least, but don't think I've rebuilt the packages with updated script, was lazy to find old microsd image where debian container was.

Will do though, though workaround can be grabbing script from the github.

**Comment by mk-fg** [comment]
> Ah yeah, apparently install scripts either create user or its home dir but not both on the first run, a mistake.

Should be fixed in 5788a02

**Comment by mk-fg** [comment]
Also, you mentioned `/etc/paging/.config` in first title and message - surely that's a mistake, should be `/home/paging/.config`, right?

**Comment by mk-fg** [comment]
Added these debs:
- paging-server_16.10.1-4_amd64
- paging-server_16.10.1-4_armhf
- pjproject_2.5.5-4_amd64
- pjproject_2.5.5-4_armhf
- python-pjsua_2.5.5-4_amd64
- python-pjsua_2.5.5-4_armhf
- python-pulsectl_16.9.11-4_amd64
- python-pulsectl_16.9.11-4_armhf

Though only thing that actually needs updating for aforementioned issue is paging-server, ofc, but I'd suggest updating pjsip and other stuff as well.
