### ISSUE TITLE
OrangePi Install Script - Debian 9 Support

### ISSUE THREAD

**Issue by danry25** [AccelerateNetworks/PagingServer#18]
Trying to run the install script on Debian 9 (Armbian w/mainline kernel) works with some minor modifications, it seems that the audio sinks are exposed a little differently is the main change.

**Comment by danry25** [comment]
Need to set the volume of the DAC and Line Out to max, add sysdefault as a fallback regex for pjsua-device, and perhaps start including a paging.wav tone with this repo.

![AlsaMixer OrangePi Paging Server Debian 9](https://user-images.githubusercontent.com/1683673/58754344-bc395680-8482-11e9-98e7-70694cfe1345.png)

**Comment by mk-fg** [comment]
I don't understand the issue tbh, can't you write regexps and configure this stuff yourself?
You can probably commit paging.wav into this repo too, sure.

**Comment by mk-fg** [comment]
Just realized that you probably left this issue here not for me to look at, but rather as a reminder to update the setup script yourself, so pls disregard earlier comment.

**Comment by danry25** [comment]
This was a TODO for me to do :P

I think the hard parts of it are done, should be able to commit the paging.wav file and config changes soon (still tweaking them to my liking).
